// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD481UKWoYG5fsB5RmruOPEteXH6h5n2LE',
    appId: '1:562618271703:web:5e683c7f116a907de5ed92',
    messagingSenderId: '562618271703',
    projectId: 'findmybus-e73c3',
    authDomain: 'findmybus-e73c3.firebaseapp.com',
    storageBucket: 'findmybus-e73c3.firebasestorage.app',
    measurementId: 'G-G15RK44FQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtSVAgCktCyfLtv_uGonimi2pR5uHEQNQ',
    appId: '1:562618271703:android:082380ed93063641e5ed92',
    messagingSenderId: '562618271703',
    projectId: 'findmybus-e73c3',
    storageBucket: 'findmybus-e73c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ny6C3aqUU-VjgzaCA5odWI0DAN-OwEM',
    appId: '1:562618271703:ios:717b7a7087b31e83e5ed92',
    messagingSenderId: '562618271703',
    projectId: 'findmybus-e73c3',
    storageBucket: 'findmybus-e73c3.firebasestorage.app',
    iosBundleId: 'com.example.findmybus',
  );
}
